server:
  port: 8082
spring:
  application:
    name: message-service
  datasource:
    url: jdbc:h2:mem:message-db
    username: sa
    password:
  h2:
    console:
      enabled: true
  cloud:
    discovery:
      enabled: true
  jpa:
    show-sql: true

